version: '3'

tasks:
  run-plan:
    internal: true
    preconditions:
      - sh: "netstat -tuln | grep ':8083.*LISTEN' >/dev/null"
        msg: "No localhost:8083. Forward ssh port first!"
    cmds:
      - echo "Running plan"
      - rm {{.RESULTS_FILE}}
      - rm -rf {{.REPORT_DIR}}/*
      - jmeter -n -t {{.PLAN_FILE}} -l {{.RESULTS_FILE}} -e -o {{.REPORT_DIR}}
    sources:
      - "{{.PLAN_FILE}}"
    generates:
      - "{{.RESULTS_FILE}}"
      - "{{.REPORT_DIR}}/index.html"

  load:
    cmds:
      - task: run-plan
        vars:
          PLAN_FILE: './load/load-test-plan.jmx'
          RESULTS_FILE: './load/load.csv'
          REPORT_DIR: './load_report'

  stress:
    cmds:
      - task: run-plan
        vars:
          PLAN_FILE: './stress/stress-test-plan.jmx'
          RESULTS_FILE: './stress/stress.csv'
          REPORT_DIR: './stress_report'

  open-load-report:
    dir: ./load_report
    deps: [load]
    cmds:
      - firefox index.html

  open-stress-report:
    dir: ./stress_report
    deps: [stress]
    cmds:
      - firefox index.html
