version: '3'

tasks:
  run-plan:
    internal: true
    preconditions:
      - sh: "netstat -tuln | grep ':8083.*LISTEN' >/dev/null"
        msg: "No localhost:8083. Forward ssh port first!"
    cmds:
      - echo "Running plan"
      - rm {{.RESULTS_FILE}}
      - test -e "{{.REPORT_DIR}}/index.html" && rm -r {{.REPORT_DIR}}/* || true
      - jmeter -n -t {{.PLAN_FILE}} -l {{.RESULTS_FILE}}
    sources:
      - "{{.PLAN_FILE}}"
    generates:
      - "{{.RESULTS_FILE}}"

  gen-report:
    internal: true
    cmds:
      - echo "Generating report"
      - test -e {{.REPORT_DIR}}/index.html && rm -r {{.REPORT_DIR}}/* || true
      - jmeter -g {{.RESULTS_FILE}} -o {{.REPORT_DIR}}
    sources:
      - "{{.RESULTS_FILE}}"
    generates:
      - "{{.REPORT_DIR}}/index.html"

  load:
    cmds:
      - task: run-plan
        vars:
          PLAN_FILE: './load/load-test-plan.jmx'
          RESULTS_FILE: './load/load.csv'
      - task: gen-report
        vars:
          RESULTS_FILE: './load/load.csv'
          REPORT_DIR: './load_report'

  stress:
    cmds:
      - task: run-plan
        vars:
          PLAN_FILE: './stress/stress-test-plan.jmx'
          RESULTS_FILE: './stress/stress.csv'

  load-report:
    dir: ./load_report
    cmds:
      - task: gen-report
        vars:
          RESULTS_FILE: './load/load.csv'
          REPORT_DIR: './load_report'
      - firefox index.html

  stress-report:
    dir: ./stress_report
    cmds:
      - task: gen-report
        vars:
          RESULTS_FILE: './stress/stress.csv'
          REPORT_DIR: './stress_report'
      - firefox index.html
